"""
Candidate Graph Ranking Engine
==============================

Ranks candidate causal graph evolutions generated by the
GraphEvolutionEngine.

Ranking criteria
1. Propagation Plausibility
2. Change Consistency
3. Graph Stability
4. Parsimony

Current default weights:
    Propagation Plausibility : 0.40
    Change Consistency       : 0.30
    Graph Stability          : 0.20
    Parsimony                : 0.10

Important
---------
This module ranks candidate GRAPH EVOLUTIONS.

A candidate graph is not a replacement for the stored/base graph.

The ranking engine never mutates the base graph.

The eventual graph-update stage will apply the selected evolution
to the existing base graph.
"""


from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from openpyxl import Workbook
from openpyxl.styles import Font

@dataclass
class RankedCandidate:
    """
    Stores one candidate together with all ranking components.
    """

    rank: int
    candidate_index: int
    candidate_state: Any
    propagation_plausibility: float
    change_consistency: float
    graph_stability: float
    parsimony: float
    final_score: float
    interaction_plan: str
    interaction_level: int
    propagation_rule: str
    structural_changes: int
    topology_changes: int
    weight_changes: int
    is_top_rank: bool = False
    tie_group: Optional[int] = None


@dataclass
class RankingResult:

    ranked_candidates: List[RankedCandidate]
    top_candidates: List[RankedCandidate]
    highest_score: Optional[float]
    has_tie: bool
    total_candidates: int
    unique_scores: int
    weight_propagation: float
    weight_change_consistency: float
    weight_stability: float
    weight_parsimony: float
    ranking_method: str = (
        "Weighted multi-criteria candidate graph evolution ranking"
    )

    def summary(self) -> Dict:
        return {
            "TotalCandidates":
                self.total_candidates,

            "HighestFinalScore":
                self.highest_score,

            "TopCandidateCount":
                len(
                    self.top_candidates
                ),

            "HasTopRankTie":
                self.has_tie,

            "PropagationWeight":
                self.weight_propagation,

            "ChangeConsistencyWeight":
                self.weight_change_consistency,

            "StabilityWeight":
                self.weight_stability,

            "ParsimonyWeight":
                self.weight_parsimony,

            "RankingMethod":
                self.ranking_method
        }

class CandidateRankingEngine:
    """
    Ranks candidate graph evolutions.

    The ranking is based on four criteria:
        Propagation Plausibility
        Change Consistency
        Graph Stability
        Parsimony

    The engine does not mutate graphs.
    """

    SCORE_ATTRIBUTE = (
        "candidate_probability"
    )

    def __init__(
        self,
        weight_propagation: float = 0.40,
        weight_change_consistency: float = 0.30,
        weight_stability: float = 0.20,
        weight_parsimony: float = 0.10,
        tie_tolerance: float = 1e-9,
        weight_similarity_scale: float = 1.0
    ):
        """
        Parameters
        ----------
        weight_similarity_scale :
            Controls how quickly edge-weight differences reduce
            the weight-similarity component.

            1.0 means a difference of 1.0 in normalized edge
            weight contributes fully to the distance.
        """

        total_weight = (
            weight_propagation
            +
            weight_change_consistency
            +
            weight_stability
            +
            weight_parsimony
        )

        if total_weight <= 0:
            raise ValueError(
                "Ranking weights must have a positive sum."
            )

        self.weight_propagation = (
            weight_propagation
            /
            total_weight
        )

        self.weight_change_consistency = (
            weight_change_consistency
            /
            total_weight
        )

        self.weight_stability = (
            weight_stability
            /
            total_weight
        )

        self.weight_parsimony = (
            weight_parsimony
            /
            total_weight
        )

        self.tie_tolerance = (
            tie_tolerance
        )

        self.weight_similarity_scale = (
            weight_similarity_scale
        )

    @staticmethod
    def _safe_float(
        value: Any,
        default: float = 0.0
    ) -> float:
        """
        Safely convert a value to float.
        """

        try:
            return float(
                value
            )

        except (
            TypeError,
            ValueError
        ):
            return default

    @staticmethod
    def _clamp(
        value: float,
        minimum: float = 0.0,
        maximum: float = 1.0
    ) -> float:
        """
        Clamp a value.
        """

        return max(
            minimum,
            min(
                maximum,
                value
            )
        )

    def _get_graph(
        self,
        state: Any
    ):
        """
        Extract a NetworkX graph from a causal state.
        """

        if state is None:
            return None

        # Direct NetworkX graph.
        if (
            hasattr(
                state,
                "nodes"
            )
            and
            hasattr(
                state,
                "edges"
            )
        ):
            return state

        # CausalState.graph
        graph = getattr(
            state,
            "graph",
            None
        )

        if graph is not None:
            return graph

        # CausalState.causal_graph
        graph = getattr(
            state,
            "causal_graph",
            None
        )

        if graph is not None:
            return graph

        return None

    def _get_edges(
        self,
        state: Any
    ) -> set:
        """
        Return directed edge set.
        """

        graph = self._get_graph(
            state
        )

        if graph is None:
            return set()

        try:
            return {
                (
                    source,
                    target
                )
                for source, target
                in graph.edges()
            }

        except Exception:
            return set()

    def _get_nodes(
        self,
        state: Any
    ) -> set:
        """
        Return graph nodes.
        """

        graph = self._get_graph(
            state
        )

        if graph is None:
            return set()

        try:
            return set(
                graph.nodes()
            )

        except Exception:
            return set()

    def _get_edge_weight(
        self,
        graph: Any,
        edge: Tuple
    ) -> float:
        """
        Extract an edge weight.

        If the edge has no explicit weight, 1.0 is used.

        This keeps topology-only graphs compatible with the
        weight-aware stability calculation.
        """

        if graph is None:
            return 1.0

        try:
            data = graph.get_edge_data(
                edge[0],
                edge[1],
                default={}
            )

        except Exception:
            return 1.0

        if not isinstance(
            data,
            dict
        ):
            return 1.0

        weight = data.get(
            "weight",
            1.0
        )

        return self._safe_float(
            weight,
            default=1.0
        )

    def _get_weight_map(
        self,
        state: Any
    ) -> Dict[Tuple, float]:
        """
        Return:
            edge -> weight

        for all edges in a graph.
        """

        graph = self._get_graph(
            state
        )

        if graph is None:
            return {}

        weight_map = {}

        try:
            edges = graph.edges()
            for source, target in edges:
                edge = (
                    source,
                    target
                )

                weight_map[edge] = (
                    self._get_edge_weight(
                        graph,
                        edge
                    )
                )

        except Exception:
            return {}

        return weight_map

    def _normalize_primary_change(
        self,
        change: Any
    ) -> Dict:
        """
        Normalize a primary change representation.
        """

        if isinstance(
            change,
            dict
        ):
            return change

        result = {}

        change_type = getattr(
            change,
            "type",
            None
        )

        edge = getattr(
            change,
            "edge",
            None
        )

        node = getattr(
            change,
            "node",
            None
        )

        weight = getattr(
            change,
            "weight",
            None
        )

        old_weight = getattr(
            change,
            "old_weight",
            None
        )

        new_weight = getattr(
            change,
            "new_weight",
            None
        )

        if change_type is not None:
            result["type"] = (
                change_type
            )

        if edge is not None:
            result["edge"] = (
                edge
            )

        if node is not None:
            result["node"] = (
                node
            )

        if weight is not None:
            result["weight"] = (
                weight
            )

        if old_weight is not None:
            result["old_weight"] = (
                old_weight
            )

        if new_weight is not None:
            result["new_weight"] = (
                new_weight
            )

        return result

    def _get_change_type(
        self,
        change: Dict
    ) -> str:
        """
        Normalize change type.
        """

        return str(
            change.get(
                "type",
                ""
            )
        ).upper()

    def _get_change_edge(
        self,
        change: Dict
    ) -> Optional[Tuple]:
        """
        Extract an edge from a primary change.
        """

        edge = change.get(
            "edge"
        )

        if edge is None:
            return None

        try:
            source, target = edge

            return (
                source,
                target
            )

        except (
            TypeError,
            ValueError
        ):
            return None

    # Criterion 1
    # Propagation Plausibility
    def _get_propagation_plausibility(
        self,
        candidate: Any
    ) -> float:

        score = getattr(
            candidate,
            self.SCORE_ATTRIBUTE,
            None
        )

        if score is None:
            score = getattr(
                candidate,
                "plausibility_score",
                None
            )

        return self._clamp(
            self._safe_float(
                score,
                default=0.0
            )
        )

    def _get_notes(
        self,
        candidate: Any
    ) -> Dict:
        """
        Extract candidate notes.
        """

        notes = getattr(
            candidate,
            "notes",
            {}
        )

        if not isinstance(
            notes,
            dict
        ):
            return {}

        return notes

    def _get_interaction_plan(
        self,
        candidate: Any
    ) -> str:
        """
        Extract interaction plan.
        """

        notes = self._get_notes(
            candidate
        )

        return str(
            notes.get(
                "InteractionPlan",
                notes.get(
                    "EvolutionOperator",
                    "Unknown"
                )
            )
        )

    def _get_interaction_level(
        self,
        candidate: Any
    ) -> int:
        """
        Extract interaction level.
        """

        notes = self._get_notes(
            candidate
        )

        value = notes.get(
            "InteractionLevel",
            0
        )

        try:
            return int(
                value
            )

        except (
            TypeError,
            ValueError
        ):
            return 0

    def _get_propagation_rule(
        self,
        candidate: Any
    ) -> str:
        """
        Extract propagation rule.
        """

        notes = self._get_notes(
            candidate
        )

        return str(
            notes.get(
                "PropagationRule",
                "Unknown"
            )
        )

    def _get_evolution_text(
        self,
        candidate: Any
    ) -> str:
        """
        Return a combined lower-case textual description of
        the candidate evolution.

        This is used only as a fallback when explicit metadata
        is unavailable.
        """

        notes = self._get_notes(
            candidate
        )

        values = []

        for key in (
            "InteractionPlan",
            "EvolutionOperator",
            "PropagationRule"
        ):

            value = notes.get(
                key
            )

            if value is not None:
                values.append(
                    str(value)
                )

        return " ".join(
            values
        ).lower()

    def _weight_changed_edges_from_primary_changes(
        self,
        primary_changes: List[Dict]
    ) -> set:
        """
        Extract edges explicitly identified by the Change Gate as
        weight-changed edges.
        """

        result = set()

        for raw_change in primary_changes:
            change = (
                self._normalize_primary_change(
                    raw_change
                )
            )

            change_type = (
                self._get_change_type(
                    change
                )
            )

            if change_type not in {
                "WEIGHT_CHANGE",
                "WEIGHT_CHANGED",
                "WEIGHT_CHANGED_EDGE"
            }:
                continue

            edge = (
                self._get_change_edge(
                    change
                )
            )

            if edge is not None:
                result.add(
                    edge
                )

        return result

    def _infer_weight_change_edges_from_candidate(
        self,
        candidate: Any,
        base_state: Any
    ) -> set:
        """
        Detect edge-weight differences between the base and candidate
        graphs.

        This catches weight modifications even when the topology is
        unchanged.
        """

        base_weights = (
            self._get_weight_map(
                base_state
            )
        )

        candidate_weights = (
            self._get_weight_map(
                candidate
            )
        )

        common_edges = (
            set(
                base_weights
            )
            &
            set(
                candidate_weights
            )
        )

        changed_edges = set()

        for edge in common_edges:
            base_weight = (
                base_weights[
                    edge
                ]
            )

            candidate_weight = (
                candidate_weights[
                    edge
                ]
            )

            if abs(
                base_weight
                -
                candidate_weight
            ) > 1e-9:
                changed_edges.add(
                    edge
                )

        return changed_edges

    # Criterion 2
    # Change Consistency
    def _change_is_satisfied(
        self,
        change: Dict,
        candidate: Any,
        base_state: Any
    ) -> bool:

        change_type = (
            self._get_change_type(
                change
            )
        )

        edge = (
            self._get_change_edge(
                change
            )
        )

        base_edges = (
            self._get_edges(
                base_state
            )
        )

        candidate_edges = (
            self._get_edges(
                candidate
            )
        )

        # EDGE ADDITION
        if change_type in {
            "EDGE_ADDITION",
            "ADDED_EDGE"
        }:

            if edge is None:
                return False

            return (
                edge not in base_edges
                and
                edge in candidate_edges
            )

        # EDGE REMOVAL
        if change_type in {
            "EDGE_REMOVAL",
            "REMOVED_EDGE"
        }:

            if edge is None:
                return False

            return (
                edge in base_edges
                and
                edge not in candidate_edges
            )

        # WEIGHT CHANGE
        if change_type in {
            "WEIGHT_CHANGE",
            "WEIGHT_CHANGED",
            "WEIGHT_CHANGED_EDGE"
        }:

            if edge is None:
                return False

            base_weights = (
                self._get_weight_map(
                    base_state
                )
            )

            candidate_weights = (
                self._get_weight_map(
                    candidate
                )
            )

            if edge not in base_weights:
                return False

            if edge not in candidate_weights:
                return False

            return (
                abs(
                    base_weights[edge]
                    -
                    candidate_weights[edge]
                )
                >
                1e-9
            )

        # ISOLATED NODE
        if change_type in {
            "ISOLATED_NODE",
            "ISOLATION",
            "NODE_ISOLATION"
        }:

            node = change.get(
                "node"
            )

            if node is None:
                return False

            base_edges_for_node = [
                edge
                for edge
                in base_edges
                if (
                    edge[0] == node
                    or
                    edge[1] == node
                )
            ]

            candidate_edges_for_node = [
                edge
                for edge
                in candidate_edges
                if (
                    edge[0] == node
                    or
                    edge[1] == node
                )
            ]

            # The candidate should introduce connectivity
            # for the affected node.
            return (
                len(
                    candidate_edges_for_node
                )
                >
                len(
                    base_edges_for_node
                )
            )

        return False


    def _get_change_consistency(
        self,
        candidate: Any,
        base_state: Any,
        primary_changes: Optional[List[Dict]]
    ) -> float:
        """
        Measure how consistently a candidate graph implements the
        detected primary changes.

        Each primary change is evaluated independently.

        A candidate receives credit only when the corresponding
        structural
        change is actually represented in the candidate graph.

        The final score is:

            Change Consistency =
                satisfied_primary_changes
                /
                total_primary_changes

        Therefore:

            all changes satisfied -> 1.0
            3 / 4 satisfied       -> 0.75
            2 / 4 satisfied       -> 0.50
            1 / 4 satisfied       -> 0.25
            0 / 4 satisfied       -> 0.00

        This deliberately evaluates the actual identity of each
        primary change rather than merely counting the number of
        structural operations performed by the candidate.
        """

        if not primary_changes:

            return 1.0

        base_graph = (
            base_state.graph
        )

        candidate_graph = (
            candidate.graph
        )

        satisfied_changes = 0

        total_changes = len(
            primary_changes
        )

        for change in primary_changes:

            if not isinstance(
                change,
                dict
            ):

                continue

            change_type = (
                change.get(
                    "type"
                )
            )

            # ======================================================
            # EDGE ADDITION
            # ======================================================

            if change_type == "EDGE_ADDITION":

                edge = (
                    change.get(
                        "edge"
                    )
                )

                if (
                    edge is not None
                    and
                    candidate_graph.has_edge(
                        edge[0],
                        edge[1]
                    )
                    and
                    not base_graph.has_edge(
                        edge[0],
                        edge[1]
                    )
                ):

                    satisfied_changes += 1

            # ======================================================
            # EDGE REMOVAL
            # ======================================================

            elif change_type == "EDGE_REMOVAL":

                edge = (
                    change.get(
                        "edge"
                    )
                )

                if (
                    edge is not None
                    and
                    base_graph.has_edge(
                        edge[0],
                        edge[1]
                    )
                    and
                    not candidate_graph.has_edge(
                        edge[0],
                        edge[1]
                    )
                ):

                    satisfied_changes += 1

            # ======================================================
            # WEIGHT CHANGE
            # ======================================================

            elif change_type in (
                "WEIGHT_CHANGE",
                "WEIGHT_CHANGED"
            ):

                edge = (
                    change.get(
                        "edge"
                    )
                )

                if (
                    edge is None
                    or
                    not base_graph.has_edge(
                        edge[0],
                        edge[1]
                    )
                    or
                    not candidate_graph.has_edge(
                        edge[0],
                        edge[1]
                    )
                ):

                    continue

                old_weight = (
                    change.get(
                        "old_weight"
                    )
                )

                new_weight = (
                    change.get(
                        "new_weight"
                    )
                )

                candidate_old_weight = (
                    base_graph[
                        edge[0]
                    ][
                        edge[1]
                    ].get(
                        "weight"
                    )
                )

                candidate_new_weight = (
                    candidate_graph[
                        edge[0]
                    ][
                        edge[1]
                    ].get(
                        "weight"
                    )
                )

                old_matches = (
                    self._weights_equal(
                        candidate_old_weight,
                        old_weight
                    )
                )

                new_matches = (
                    self._weights_equal(
                        candidate_new_weight,
                        new_weight
                    )
                )

                if (
                    old_matches
                    and
                    new_matches
                ):

                    satisfied_changes += 1

            # ======================================================
            # ISOLATED NODE
            # ======================================================

            elif change_type == "ISOLATED_NODE":

                node = (
                    change.get(
                        "node"
                    )
                )

                if node is None:

                    continue

                # The primary change says that this node became
                # isolated in the newly observed/current state.
                #
                # A candidate consistently implementing that change
                # should preserve the node's isolated state unless
                # the candidate explicitly proposes a recovery
                # action for that node.
                #
                # Therefore:
                #
                #     Base graph connected
                #     Candidate graph isolated
                #
                # is considered a direct implementation of the
                # detected isolation change.

                base_degree = (
                    base_graph.degree(
                        node
                    )
                    if node in base_graph
                    else 0
                )

                candidate_degree = (
                    candidate_graph.degree(
                        node
                    )
                    if node in candidate_graph
                    else 0
                )

                if (
                    base_degree > 0
                    and
                    candidate_degree == 0
                ):

                    satisfied_changes += 1

            # ======================================================
            # UNKNOWN CHANGE TYPE
            # ======================================================

            else:

                continue

        return (
            satisfied_changes
            /
            total_changes
        )
    # def _get_change_consistency(
    #     self,
    #     candidate: Any,
    #     base_state: Any,
    #     primary_changes: List[Dict]
    # ) -> float:

    #     if not primary_changes:
    #         return 1.0

    #     satisfied = 0

    #     normalized_changes = [
    #         self._normalize_primary_change(
    #             change
    #         )
    #         for change in primary_changes
    #     ]

    #     for change in normalized_changes:
    #         if self._change_is_satisfied(
    #             change,
    #             candidate,
    #             base_state
    #         ):
    #             satisfied += 1

    #     return self._clamp(
    #         satisfied
    #         /
    #         len(
    #             normalized_changes
    #         )
    #     )

    # Criterion 3
    # Graph Stability
    def _get_topological_stability(
        self,
        candidate: Any,
        base_state: Any
    ) -> float:
        """
        Topological Jaccard similarity.
        """

        base_edges = (
            self._get_edges(
                base_state
            )
        )

        candidate_edges = (
            self._get_edges(
                candidate
            )
        )

        union = (
            base_edges
            |
            candidate_edges
        )

        intersection = (
            base_edges
            &
            candidate_edges
        )

        if not union:
            return 1.0

        return self._clamp(
            len(
                intersection
            )
            /
            len(
                union
            )
        )

    def _get_weight_stability(
        self,
        candidate: Any,
        base_state: Any
    ) -> float:
        """
        Weight similarity for common edges.

        A common edge with identical weight contributes 1.0.
        A common edge with a different weight contributes less.

        Edges present in only one graph are handled by the
        topological stability component rather than being treated
        as a weight comparison.
        """

        base_weights = (
            self._get_weight_map(
                base_state
            )
        )

        candidate_weights = (
            self._get_weight_map(
                candidate
            )
        )

        common_edges = (
            set(
                base_weights
            )
            &
            set(
                candidate_weights
            )
        )

        if not common_edges:
            return 1.0

        similarities = []

        for edge in common_edges:
            base_weight = (
                base_weights[
                    edge
                ]
            )

            candidate_weight = (
                candidate_weights[
                    edge
                ]
            )

            difference = abs(
                base_weight
                -
                candidate_weight
            )

            # Exponential decay keeps the score within [0, 1].
            similarity = (
                1.0
                /
                (
                    1.0
                    +
                    (
                        self.weight_similarity_scale
                        *
                        difference
                    )
                )
            )

            similarities.append(
                self._clamp(
                    similarity
                )
            )

        return self._clamp(
            sum(
                similarities
            )
            /
            len(
                similarities
            )
        )

    def _get_graph_stability(
        self,
        candidate: Any,
        base_state: Any
    ) -> float:
        """
        The final stability score combines:
            70% topology preservation
            30% weight preservation
        """

        topology = (
            self._get_topological_stability(
                candidate,
                base_state
            )
        )

        weight = (
            self._get_weight_stability(
                candidate,
                base_state
            )
        )

        return self._clamp(
            (
                0.70
                *
                topology
            )
            +
            (
                0.30
                *
                weight
            )
        )

    # Criterion 4
    # Parsimony
    def _get_topology_change_count(
        self,
        candidate: Any,
        base_state: Any
    ) -> int:
        """
        Number of added/removed edges.
        """

        base_edges = (
            self._get_edges(
                base_state
            )
        )

        candidate_edges = (
            self._get_edges(
                candidate
            )
        )

        return len(
            base_edges
            ^
            candidate_edges
        )

    def _get_weight_change_count(
        self,
        candidate: Any,
        base_state: Any
    ) -> int:
        """
        Number of edges whose weights changed.
        """

        return len(
            self._infer_weight_change_edges_from_candidate(
                candidate,
                base_state
            )
        )

    def _get_parsimony(
        self,
        candidate: Any,
        base_state: Any
    ) -> float:
        """
        A topological modification counts as one operation.
        A weight modification also counts as one operation.

        Therefore:
            0 modifications -> 1.0
            1 modification  -> 0.5
            2 modifications -> 0.333...
            ...

        This makes weight changes visible to the parsimony
        criterion even when topology is unchanged.
        """

        topology_changes = (
            self._get_topology_change_count(
                candidate,
                base_state
            )
        )

        weight_changes = (
            self._get_weight_change_count(
                candidate,
                base_state
            )
        )

        total_operations = (
            topology_changes
            +
            weight_changes
        )

        return self._clamp(
            1.0
            /
            (
                1.0
                +
                total_operations
            )
        )

    def _get_structural_change_count(
        self,
        candidate: Any,
        base_state: Any
    ) -> int:
        """
        Total number of graph-evolution operations.
        Includes:
            topology changes
            +
            weight changes
        """

        topology_changes = (
            self._get_topology_change_count(
                candidate,
                base_state
            )
        )

        weight_changes = (
            self._get_weight_change_count(
                candidate,
                base_state
            )
        )

        return (
            topology_changes
            +
            weight_changes
        )

    def _calculate_final_score(
        self,
        propagation: float,
        change_consistency: float,
        stability: float,
        parsimony: float
    ) -> float:
        """
        Calculate weighted final ranking score.
        """

        score = (
            self.weight_propagation
            *
            propagation

            +

            self.weight_change_consistency
            *
            change_consistency

            +

            self.weight_stability
            *
            stability

            +

            self.weight_parsimony
            *
            parsimony
        )

        return self._clamp(
            score
        )

    def rank(
        self,
        candidates: List[Any],
        base_state: Any,
        primary_changes: Optional[List[Dict]] = None
    ) -> RankingResult:
        """
        Rank candidate graph evolutions.

        Parameters
        ----------
        candidates:
            Candidate graph states.

        base_state:
            Original stored/base causal graph.

        primary_changes:
            Changes detected by the Change Gate.
        """

        if candidates is None:
            candidates = []

        if primary_changes is None:
            primary_changes = []

        if not candidates:
            return RankingResult(
                ranked_candidates=[],
                top_candidates=[],
                highest_score=None,
                has_tie=False,
                total_candidates=0,
                unique_scores=0,

                weight_propagation=
                    self.weight_propagation,

                weight_change_consistency=
                    self.weight_change_consistency,

                weight_stability=
                    self.weight_stability,

                weight_parsimony=
                    self.weight_parsimony
            )

        scored_candidates = []

        for index, candidate in enumerate(
            candidates,
            start=1
        ):
            propagation = (
                self._get_propagation_plausibility(
                    candidate
                )
            )

            change_consistency = (
                self._get_change_consistency(
                    candidate,
                    base_state,
                    primary_changes
                )
            )

            stability = (
                self._get_graph_stability(
                    candidate,
                    base_state
                )
            )

            parsimony = (
                self._get_parsimony(
                    candidate,
                    base_state
                )
            )

            topology_changes = (
                self._get_topology_change_count(
                    candidate,
                    base_state
                )
            )

            weight_changes = (
                self._get_weight_change_count(
                    candidate,
                    base_state
                )
            )

            structural_changes = (
                topology_changes
                +
                weight_changes
            )

            final_score = (
                self._calculate_final_score(
                    propagation,
                    change_consistency,
                    stability,
                    parsimony
                )
            )

            scored_candidates.append(
                (
                    index,
                    candidate,
                    propagation,
                    change_consistency,
                    stability,
                    parsimony,
                    final_score,
                    structural_changes,
                    topology_changes,
                    weight_changes
                )
            )

        # Sort by final score.
        scored_candidates.sort(
            key=lambda item: item[6],
            reverse=True
        )

        ranked_candidates = []
        previous_score = None
        current_rank = 1
        tie_group = 1

        for position, item in enumerate(
            scored_candidates
        ):
            (
                original_index,
                candidate,
                propagation,
                change_consistency,
                stability,
                parsimony,
                final_score,
                structural_changes,
                topology_changes,
                weight_changes
            ) = item

            if position == 0:
                current_rank = 1
                tie_group = 1

            else:
                scores_equal = (
                    abs(
                        final_score
                        -
                        previous_score
                    )
                    <=
                    self.tie_tolerance
                )

                if not scores_equal:
                    current_rank = (
                        position + 1
                    )

                    tie_group += 1

            ranked = RankedCandidate(
                rank=current_rank,

                candidate_index=
                    original_index,

                candidate_state=
                    candidate,

                propagation_plausibility=
                    propagation,

                change_consistency=
                    change_consistency,

                graph_stability=
                    stability,

                parsimony=
                    parsimony,

                final_score=
                    final_score,

                interaction_plan=
                    self._get_interaction_plan(
                        candidate
                    ),

                interaction_level=
                    self._get_interaction_level(
                        candidate
                    ),

                propagation_rule=
                    self._get_propagation_rule(
                        candidate
                    ),

                structural_changes=
                    structural_changes,

                topology_changes=
                    topology_changes,

                weight_changes=
                    weight_changes,

                is_top_rank=(
                    current_rank == 1
                ),

                tie_group=
                    tie_group
            )

            ranked_candidates.append(
                ranked
            )

            previous_score = (
                final_score
            )

        top_candidates = [
            candidate
            for candidate
            in ranked_candidates
            if candidate.rank == 1
        ]

        has_tie = (
            len(
                top_candidates
            )
            >
            1
        )

        # Unique score levels
        unique_scores = []

        for item in scored_candidates:
            score = item[6]

            if not any(
                abs(
                    score
                    -
                    existing
                )
                <=
                self.tie_tolerance

                for existing
                in unique_scores
            ):
                unique_scores.append(
                    score
                )

        return RankingResult(
            ranked_candidates=
                ranked_candidates,

            top_candidates=
                top_candidates,

            highest_score=
                ranked_candidates[0].final_score,

            has_tie=
                has_tie,

            total_candidates=
                len(candidates),

            unique_scores=
                len(unique_scores),

            weight_propagation=
                self.weight_propagation,

            weight_change_consistency=
                self.weight_change_consistency,

            weight_stability=
                self.weight_stability,

            weight_parsimony=
                self.weight_parsimony
        )

    def export_to_excel(
        self,
        result: RankingResult,
        output_path: str =
            "results/graphs/candidate_ranking.xlsx"
    ):
        """
        Export the complete ranking to Excel.
        """

        output_file = Path(
            output_path
        )

        output_file.parent.mkdir(
            parents=True,
            exist_ok=True
        )

        workbook = Workbook()

        summary = (
            workbook.active
        )

        summary.title = (
            "Summary"
        )

        summary_rows = [
            (
                "Metric",
                "Value"
            ),

            (
                "Total Candidates",
                result.total_candidates
            ),

            (
                "Highest Final Score",
                result.highest_score
            ),

            (
                "Top-Ranked Candidates",
                len(
                    result.top_candidates
                )
            ),

            (
                "Top-Rank Tie",
                result.has_tie
            ),

            (
                "Unique Final Score Levels",
                result.unique_scores
            ),

            (
                "Propagation Weight",
                result.weight_propagation
            ),

            (
                "Change Consistency Weight",
                result.weight_change_consistency
            ),

            (
                "Graph Stability Weight",
                result.weight_stability
            ),

            (
                "Parsimony Weight",
                result.weight_parsimony
            ),

            (
                "Ranking Method",
                result.ranking_method
            )
        ]

        for row in summary_rows:
            summary.append(
                row
            )

        for cell in summary[1]:
            cell.font = (
                Font(
                    bold=True
                )
            )

        summary.column_dimensions[
            "A"
        ].width = 38

        summary.column_dimensions[
            "B"
        ].width = 60

        ranked_sheet = (
            workbook.create_sheet(
                "Ranked Candidates"
            )
        )

        ranked_sheet.append(
            [
                "Rank",
                "Original Candidate ID",
                "Final Score",
                "Propagation Plausibility",
                "Change Consistency",
                "Graph Stability",
                "Parsimony",
                "Structural Changes",
                "Topology Changes",
                "Weight Changes",
                "Interaction Plan",
                "Interaction Level",
                "Propagation Rule",
                "Tie Group",
                "Top Rank"
            ]
        )

        for cell in ranked_sheet[1]:
            cell.font = (
                Font(
                    bold=True
                )
            )

        for ranked in (
            result.ranked_candidates
        ):

            ranked_sheet.append(
                [
                    ranked.rank,
                    ranked.candidate_index,
                    ranked.final_score,
                    ranked.propagation_plausibility,
                    ranked.change_consistency,
                    ranked.graph_stability,
                    ranked.parsimony,
                    ranked.structural_changes,
                    ranked.topology_changes,
                    ranked.weight_changes,
                    ranked.interaction_plan,
                    ranked.interaction_level,
                    ranked.propagation_rule,
                    ranked.tie_group,
                    ranked.is_top_rank
                ]
            )

        ranked_sheet.freeze_panes = (
            "A2"
        )

        ranked_sheet.auto_filter.ref = (
            ranked_sheet.dimensions
        )

        widths = {
            "A": 10,
            "B": 22,
            "C": 16,
            "D": 25,
            "E": 22,
            "F": 20,
            "G": 16,
            "H": 20,
            "I": 18,
            "J": 16,
            "K": 85,
            "L": 18,
            "M": 35,
            "N": 12,
            "O": 12
        }

        for column, width in (
            widths.items()
        ):

            ranked_sheet.column_dimensions[
                column
            ].width = width

        top_sheet = (
            workbook.create_sheet(
                "Top Candidates"
            )
        )

        top_sheet.append(
            [
                "Rank",
                "Original Candidate ID",
                "Final Score",
                "Propagation Plausibility",
                "Change Consistency",
                "Graph Stability",
                "Parsimony",
                "Structural Changes",
                "Topology Changes",
                "Weight Changes",
                "Interaction Plan",
                "Interaction Level",
                "Propagation Rule",
                "Tie Group"
            ]
        )

        for cell in top_sheet[1]:
            cell.font = (
                Font(
                    bold=True
                )
            )

        for ranked in (
            result.top_candidates
        ):

            top_sheet.append(
                [
                    ranked.rank,
                    ranked.candidate_index,
                    ranked.final_score,
                    ranked.propagation_plausibility,
                    ranked.change_consistency,
                    ranked.graph_stability,
                    ranked.parsimony,
                    ranked.structural_changes,
                    ranked.topology_changes,
                    ranked.weight_changes,
                    ranked.interaction_plan,
                    ranked.interaction_level,
                    ranked.propagation_rule,
                    ranked.tie_group
                ]
            )

        top_sheet.freeze_panes = (
            "A2"
        )

        top_sheet.auto_filter.ref = (
            top_sheet.dimensions
        )

        for column, width in (
            widths.items()
        ):

            if column != "O":
                top_sheet.column_dimensions[
                    column
                ].width = width

        workbook.save(
            output_file
        )

        return str(
            output_file
        )

    def export_to_text(
        self,
        result: RankingResult,
        output_path: str =
            "results/reports/candidate_ranking.txt",
        top_n: int = 20
    ):
        """
        Export a compact ranking report.
        """

        output_file = Path(
            output_path
        )

        output_file.parent.mkdir(
            parents=True,
            exist_ok=True
        )

        lines = []

        lines.append(
            "=" * 80
        )

        lines.append(
            "Candidate Graph Ranking"
        )

        lines.append(
            "=" * 80
        )

        lines.append("")

        lines.append(
            f"Total Candidates : "
            f"{result.total_candidates}"
        )

        lines.append(
            f"Highest Final Score : "
            f"{result.highest_score:.4f}"
            if result.highest_score is not None
            else
            "Highest Final Score : N/A"
        )

        lines.append(
            f"Top-Ranked Candidates : "
            f"{len(result.top_candidates)}"
        )

        lines.append(
            f"Top-Rank Tie : "
            f"{'YES' if result.has_tie else 'NO'}"
        )

        lines.append(
            f"Unique Final Score Levels : "
            f"{result.unique_scores}"
        )

        lines.append("")

        lines.append(
            "Ranking Weights"
        )

        lines.append(
            f"  Propagation Plausibility : "
            f"{result.weight_propagation:.3f}"
        )

        lines.append(
            f"  Change Consistency       : "
            f"{result.weight_change_consistency:.3f}"
        )

        lines.append(
            f"  Graph Stability          : "
            f"{result.weight_stability:.3f}"
        )

        lines.append(
            f"  Parsimony                : "
            f"{result.weight_parsimony:.3f}"
        )

        lines.append("")

        lines.append(
            f"Ranking Method : "
            f"{result.ranking_method}"
        )

        lines.append("")

        lines.append(
            "-" * 80
        )

        lines.append(
            f"Top {top_n} Ranked Candidates"
        )

        lines.append(
            "-" * 80
        )

        for ranked in (
            result.ranked_candidates[
                :top_n
            ]
        ):
            lines.append("")

            lines.append(
                f"Rank : "
                f"{ranked.rank}"
            )

            lines.append(
                f"Original Candidate ID : "
                f"{ranked.candidate_index}"
            )

            lines.append(
                f"Final Score : "
                f"{ranked.final_score:.4f}"
            )

            lines.append(
                f"Propagation Plausibility : "
                f"{ranked.propagation_plausibility:.4f}"
            )

            lines.append(
                f"Change Consistency : "
                f"{ranked.change_consistency:.4f}"
            )

            lines.append(
                f"Graph Stability : "
                f"{ranked.graph_stability:.4f}"
            )

            lines.append(
                f"Parsimony : "
                f"{ranked.parsimony:.4f}"
            )

            lines.append(
                f"Structural Changes : "
                f"{ranked.structural_changes}"
            )

            lines.append(
                f"Topology Changes : "
                f"{ranked.topology_changes}"
            )

            lines.append(
                f"Weight Changes : "
                f"{ranked.weight_changes}"
            )

            lines.append(
                f"Interaction Plan : "
                f"{ranked.interaction_plan}"
            )

            lines.append(
                f"Interaction Level : "
                f"{ranked.interaction_level}"
            )

            lines.append(
                f"Propagation Rule : "
                f"{ranked.propagation_rule}"
            )

            lines.append(
                f"Tie Group : "
                f"{ranked.tie_group}"
            )

        lines.append("")

        lines.append(
            "=" * 80
        )

        lines.append(
            "End of Ranking Report"
        )

        lines.append(
            "=" * 80
        )

        with open(
            output_file,
            "w",
            encoding="utf-8"
        ) as file:

            file.write(
                "\n".join(
                    lines
                )
            )

        return str(
            output_file
        )

if __name__ == "__main__":

    from src.storage.active_graph_manager import (
        ActiveGraphManager
    )

    from src.storage.causal_state_repository import (
        CausalStateRepository
    )

    from src.change_gate.change_gate import (
        ChangeGate
    )

    from src.graph_evolution.graph_evolution_engine import (
        GraphEvolutionEngine
    )

    manager = (
        ActiveGraphManager()
    )

    repository = (
        CausalStateRepository()
    )

    stored_state = (
        manager.load()
    )

    current_states = (
        repository.load_all()
    )

    if stored_state is None:
        raise RuntimeError(
            "No stored/base causal state was found."
        )

    if not current_states:
        raise RuntimeError(
            "No current causal states were found."
        )

    current_state = (
        current_states[-1]
    )

    gate = (
        ChangeGate()
    )

    decision = (
        gate.evaluate(
            stored_state,
            current_state
        )
    )

    primary_changes = []

    if isinstance(
        decision,
        dict
    ):
        detected_changes = (
            decision.get(
                "DetectedChanges",
                {}
            )
        )

        if not isinstance(
            detected_changes,
            dict
        ):
            raise TypeError(
                "decision['DetectedChanges'] "
                "must be a dictionary."
            )

        # Edge additions
        for edge in detected_changes.get(
            "AddedEdges",
            []
        ):

            primary_changes.append(
                {
                    "type":
                        "EDGE_ADDITION",

                    "edge":
                        edge
                }
            )

        # Edge removals
        for edge in detected_changes.get(
            "RemovedEdges",
            []
        ):

            primary_changes.append(
                {
                    "type":
                        "EDGE_REMOVAL",

                    "edge":
                        edge
                }
            )

        # Weight changes
        for change in detected_changes.get(
            "WeightChangedEdges",
            []
        ):

            primary_changes.append(
                {
                    "type":
                        "WEIGHT_CHANGE",

                    "edge":
                        change["edge"],

                    "old_weight":
                        change["old_weight"],

                    "new_weight":
                        change["new_weight"]
                }
            )

        # Isolated nodes
        for node in detected_changes.get(
            "IsolatedNodes",
            []
        ):

            primary_changes.append(
                {
                    "type":
                        "ISOLATED_NODE",

                    "node":
                        node
                }
            )

    elif isinstance(
        decision,
        list
    ):

        primary_changes = (
            decision
        )
    #     primary_changes = decision.get(
    #         "PrimaryChanges",
    #         []
    #     )

    #     if not primary_changes:
    #         added_edges = (
    #             decision.get(
    #                 "AddedEdges",
    #                 []
    #             )
    #         )

    #         removed_edges = (
    #             decision.get(
    #                 "RemovedEdges",
    #                 []
    #             )
    #         )

    #         weight_changed_edges = (
    #             decision.get(
    #                 "WeightChangedEdges",
    #                 []
    #             )
    #         )

    #         isolated_nodes = (
    #             decision.get(
    #                 "IsolatedNodes",
    #                 []
    #             )
    #         )

    #         for edge in added_edges:
    #             primary_changes.append(
    #                 {
    #                     "type":
    #                         "EDGE_ADDITION",

    #                     "edge":
    #                         edge
    #                 }
    #             )

    #         for edge in removed_edges:
    #             primary_changes.append(
    #                 {
    #                     "type":
    #                         "EDGE_REMOVAL",

    #                     "edge":
    #                         edge
    #                 }
    #             )

    #         for edge in weight_changed_edges:
    #             primary_changes.append(
    #                 {
    #                     "type":
    #                         "WEIGHT_CHANGED",

    #                     "edge":
    #                         edge
    #                 }
    #             )

    #         for node in isolated_nodes:
    #             primary_changes.append(
    #                 {
    #                     "type":
    #                         "ISOLATED_NODE",

    #                     "node":
    #                         node
    #                 }
    #             )

    # elif isinstance(
    #     decision,
    #     list
    # ):
    #     primary_changes = (
    #         decision
    #     )

    evolution_engine = (
        GraphEvolutionEngine()
    )

    candidates = (
        evolution_engine.generate_candidates(
            stored_state,
            current_state,
            decision
        )
    )

    ranking_engine = (
        CandidateRankingEngine(
            weight_propagation=
                0.40,

            weight_change_consistency=
                0.30,

            weight_stability=
                0.20,

            weight_parsimony=
                0.10
        )
    )

    result = (
        ranking_engine.rank(
            candidates=
                candidates,

            base_state=
                stored_state,

            primary_changes=
                primary_changes
        )
    )

    excel_path = (
        ranking_engine.export_to_excel(
            result
        )
    )

    text_path = (
        ranking_engine.export_to_text(
            result,
            top_n=20
        )
    )

    print()
    print(
        "=" * 80
    )
    print(
        "Candidate Graph Ranking"
    )
    print(
        "=" * 80
    )
    print()

    print(
        f"Primary Changes : "
        f"{len(primary_changes)}"
    )

    print(
        f"Candidate Graphs : "
        f"{result.total_candidates}"
    )

    print(
        f"Highest Final Score : "
        f"{result.highest_score:.4f}"
        if result.highest_score is not None
        else
        "Highest Final Score : N/A"
    )

    print(
        f"Top-Ranked Candidates : "
        f"{len(result.top_candidates)}"
    )

    print(
        f"Top-Rank Tie : "
        f"{'YES' if result.has_tie else 'NO'}"
    )

    print()
    print(
        "Ranking Weights"
    )

    print(
        f"  Propagation Plausibility : "
        f"{result.weight_propagation:.3f}"
    )

    print(
        f"  Change Consistency       : "
        f"{result.weight_change_consistency:.3f}"
    )

    print(
        f"  Graph Stability          : "
        f"{result.weight_stability:.3f}"
    )

    print(
        f"  Parsimony                : "
        f"{result.weight_parsimony:.3f}"
    )

    print()
    print(
        "Results exported to:"
    )

    print(
        f"  {excel_path}"
    )

    print(
        f"  {text_path}"
    )

    print()
    print(
        "-" * 80
    )
    print(
        "Top 10 Candidates"
    )
    print(
        "-" * 80
    )

    for ranked in (
        result.ranked_candidates[
            :10
        ]
    ):
        print()

        print(
            f"Rank : "
            f"{ranked.rank}"
        )

        print(
            f"Original Candidate ID : "
            f"{ranked.candidate_index}"
        )

        print(
            f"Final Score : "
            f"{ranked.final_score:.4f}"
        )

        print(
            f"  Propagation Plausibility : "
            f"{ranked.propagation_plausibility:.4f}"
        )

        print(
            f"  Change Consistency       : "
            f"{ranked.change_consistency:.4f}"
        )

        print(
            f"  Graph Stability          : "
            f"{ranked.graph_stability:.4f}"
        )

        print(
            f"  Parsimony                : "
            f"{ranked.parsimony:.4f}"
        )

        print(
            f"  Structural Changes       : "
            f"{ranked.structural_changes}"
        )

        print(
            f"  Topology Changes         : "
            f"{ranked.topology_changes}"
        )

        print(
            f"  Weight Changes           : "
            f"{ranked.weight_changes}"
        )

        print(
            f"  Interaction Plan : "
            f"{ranked.interaction_plan}"
        )

    print()
    print(
        "=" * 80
    )
    print(
        "Ranking Complete"
    )
    print(
        "=" * 80
    )