"""
Interaction Plan

Purpose
-------
Represents a complete graph evolution hypothesis.

Every candidate graph generated by the Graph Evolution
Engine is associated with one InteractionPlan that
records:

1. Which primary changes triggered the evolution.
2. Which evolution actions were applied.
3. Which propagation rules produced those actions.
4. The execution order.
5. The cumulative plausibility score.

This enables complete traceability and explainability.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional

@dataclass
class ActionStep:
    action_name: str
    propagation_rule: str
    base_score: float
    context: Dict = field(default_factory=dict)
    execution_order: int = 0
    notes: Dict = field(default_factory=dict)

@dataclass
class PrimaryChangePlan:
    change_id: int
    change_type: str
    change: Dict
    action_steps: List[ActionStep] = field(default_factory=list)
    cumulative_score: float = 1.0
    notes: Dict = field(default_factory=dict)

    def add_action(self, action: ActionStep):
        action.execution_order = len(self.action_steps) + 1
        self.action_steps.append(action)
        self.cumulative_score *= action.base_score

@dataclass
class InteractionPlan:
    hypothesis_name: str

    primary_change_plans: List[
        PrimaryChangePlan
    ] = field(default_factory=list)

    interaction_level: int = 1
    cumulative_score: float = 1.0
    regime_profile: Optional[Dict] = None
    metadata: Dict = field(default_factory=dict)
    notes: Dict = field(default_factory=dict)

    def add_primary_change(
        self,
        plan: PrimaryChangePlan
    ):

        self.primary_change_plans.append(plan)
        self.cumulative_score *= plan.cumulative_score

    # Number of actions
    @property
    def total_actions(self):
        return sum(
            len(plan.action_steps)
            for plan in self.primary_change_plans
        )

    # Flatten all actions
    @property
    def all_actions(self):
        actions = []

        for plan in self.primary_change_plans:
            actions.extend(
                plan.action_steps
            )

        return actions

    def summary(self):
        return {
            "Hypothesis":
                self.hypothesis_name,

            "InteractionLevel":
                self.interaction_level,

            "PrimaryChanges":
                len(self.primary_change_plans),

            "Actions":
                self.total_actions,

            "Score":
                round(
                    self.cumulative_score,
                    4
                )
        }

def print_interaction_plan(
    plan: InteractionPlan
):

    print("=" * 80)
    print("Interaction Plan")
    print("=" * 80)
    print()
    print(
        f"Hypothesis : "
        f"{plan.hypothesis_name}"
    )

    print(
        f"Interaction Level : "
        f"{plan.interaction_level}"
    )

    print(
        f"Cumulative Score : "
        f"{plan.cumulative_score:.4f}"
    )

    print()

    for primary in plan.primary_change_plans:
        print(
            f"Primary Change "
            f"{primary.change_id}"
        )

        print(
            f"Type : "
            f"{primary.change_type}"
        )

        print(
            f"Details : "
            f"{primary.change}"
        )

        print()

        for step in primary.action_steps:
            print(
                f"   {step.execution_order}. "
                f"{step.action_name}"
            )

            print(
                f"      Rule : "
                f"{step.propagation_rule}"
            )

            print(
                f"      Score : "
                f"{step.base_score:.2f}"
            )

        print()

    print("=" * 80)

# Testing
if __name__ == "__main__":
    action1 = ActionStep(
        action_name="ApplyAddedEdge",
        propagation_rule="Keep Added Edge",
        base_score=1.0,
        context={
            "edge":
                ("GDP", "SP500")
        }
    )

    action2 = ActionStep(
        action_name="StrengthenDownstream",
        propagation_rule="Strengthen Downstream",
        base_score=0.75
    )

    primary = PrimaryChangePlan(
        change_id=1,
        change_type="EDGE_ADDITION",
        change={
            "edge":
                ("GDP", "SP500")
        }
    )

    primary.add_action(action1)
    primary.add_action(action2)
    interaction = InteractionPlan(
        hypothesis_name="Candidate_001",
        interaction_level=2
    )

    interaction.add_primary_change(primary)
    print_interaction_plan(interaction)